# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gzppNXheQz0F4mgIEz+/j/W1u5R81JZlcZTPGCNQ8/kJ8kjX/JfsZ2k5FjqzM4XOHET4aHxVbCMoVn3ffeQNgrf5WD2KKC5nQB2AhQvPQYeAhaYNT2Qx42jjdyGEzkNU061Fj+9ghPfBCDOfvX+IOPEgzrptRoirdteQmGnP3latLDYIZ8NBhpTO3/TKFAdxsQPFsWZpYYhiBrk9zdivIRnR2y/gmaH9Vg7t65eOHbYoszV/1tCYw6+cijY6rWojqpYUMJ2/RdAhJjBvCWOoMWqNf3QrdZT+z4Qx+zCc3fbscm84OaHz5CWX+4e5HDE7xFtnX1w9HOUP07PVVmSt2bo2HAuwUSI+8ReHFk35J2ErBGQT1uwZcPYk/cW75tQOOg6YzIM7lcJ/PpnUwWLaa6Uujsi4fEZc82UY59+kokyJoJBIWeHNnRx+tWF00B8gEVqrE8CxFdO+5y8ICejyF2XJ2AaVlFuuS72sYXhJKCnRiteIzTp1aIcacnPhZhSae0Lv8NvI/H7TZ2/d9klLiIfCSiHBeNz6kBVeA3FvEJZtUFCi5BQVQLeUt3ouCWg56sPNF7bJxteWZ+YOyS9bSEGW6s4MtuNp8MIQGGppAfKp76DBxaBRjd6Mz2SrM1wJVrrqCsHvdDlzzbBdHCvnF8tp8ZgDL4V+8ieoSQSrb2o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
