appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: c2AsooKWHva2gsi/8Gxx4/j/R1b9dsF2TN9iuV29EiSCb4Rz56+rUr0qmCujXbAe/aIcLdF5EqqJhvxrIzRvzVHme+CDaNXcB7wXRLSwbQY6XHXlfKfY0vGY/uBvV0s2abF1G0f37loWax8aoW/HwuGtt8aR0H/5/XnlRU8CTFjkfUT4sSonaK/L0iPxAmohdB+wC//zERLK/KRQnTFRBCGtZ2ffd7OAxcxPqPXReQx2QpYwjtodhK7Sl211nqjMOdXWYUG7Btvtv2ox4HVMhDSlSOv29VE8Ne8vtmqZRuuQs22/drsOcIb6rX7LE6aUG+/5etjh8s3qP/RcxyGp4Ust0C44nVHszSZHoYnQuzS07Mz5uBSkv74YR6T5iq/xNF9YyqN4edX7id8FnI9/DZZfZ6ohZmwBvV17CXGqFyvecLoabqoeaADKXuOF6koOuAadh/PUNZ2D2NzfgcTxR1N3PsuW6QqiVJqxUu5pRZ4gfaXv36dQwzz8x7hFVZ50ZMiixLl0gwyrU47aW9xtfOI4XsoKWR0okBLEy6+18jd3ZmQP7HGB2TSP4A9Sb3icWjbf6v7Nd2HLuT93UG6mhAf8l9+05QpkDwEfqTn7QpjtIzSc1N6LjVYqxH/2xVvA6FoyzN5q15gGg6ZZF9u3wAgI6fePYZefCE8XXEWqVbc=}
provider:
  win: azure
