travis:
  secure:
    BINSTAR_TOKEN: gzppNXheQz0F4mgIEz+/j/W1u5R81JZlcZTPGCNQ8/kJ8kjX/JfsZ2k5FjqzM4XOHET4aHxVbCMoVn3ffeQNgrf5WD2KKC5nQB2AhQvPQYeAhaYNT2Qx42jjdyGEzkNU061Fj+9ghPfBCDOfvX+IOPEgzrptRoirdteQmGnP3latLDYIZ8NBhpTO3/TKFAdxsQPFsWZpYYhiBrk9zdivIRnR2y/gmaH9Vg7t65eOHbYoszV/1tCYw6+cijY6rWojqpYUMJ2/RdAhJjBvCWOoMWqNf3QrdZT+z4Qx+zCc3fbscm84OaHz5CWX+4e5HDE7xFtnX1w9HOUP07PVVmSt2bo2HAuwUSI+8ReHFk35J2ErBGQT1uwZcPYk/cW75tQOOg6YzIM7lcJ/PpnUwWLaa6Uujsi4fEZc82UY59+kokyJoJBIWeHNnRx+tWF00B8gEVqrE8CxFdO+5y8ICejyF2XJ2AaVlFuuS72sYXhJKCnRiteIzTp1aIcacnPhZhSae0Lv8NvI/H7TZ2/d9klLiIfCSiHBeNz6kBVeA3FvEJZtUFCi5BQVQLeUt3ouCWg56sPNF7bJxteWZ+YOyS9bSEGW6s4MtuNp8MIQGGppAfKp76DBxaBRjd6Mz2SrM1wJVrrqCsHvdDlzzbBdHCvnF8tp8ZgDL4V+8ieoSQSrb2o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
